"use client";

import { useEffect, useMemo, useState } from "react";
import {
  Activity, ArrowRight, Check, CheckCircle2, ChevronDown, CircleAlert, Clock3,
  FileCheck2, FileText, Fingerprint, History, Inbox, Link2, LockKeyhole,
  RefreshCw, RotateCcw, Send, ShieldCheck, Sparkles, UserRoundCheck, XCircle,
} from "lucide-react";
import type { ExtractedField, FieldKey, Referral, ReferralStatus, WorkspaceState } from "@/lib/contracts";
import { workspaceSchema } from "@/lib/contracts";
import { acknowledgeReferral, assignReferral, correctField, deliverReferral, resolveIdentity, reviewExtraction, validateReferral } from "@/lib/engine";
import { createSeedState } from "@/lib/seed";
import { BENCHMARK_RESULT } from "@/lib/benchmark";

const STORAGE_KEY = "clearpath-referrals:v1";
type View = "workbench" | "handoffs" | "evidence" | "system";

const statusLabels: Record<ReferralStatus, string> = {
  NEW: "New intake", NEEDS_INFORMATION: "Needs information", READY_FOR_REVIEW: "Ready for review",
  READY_TO_SEND: "Ready to send", DELIVERY_INTERRUPTED: "Handoff failed",
  AWAITING_ACKNOWLEDGEMENT: "Awaiting acknowledgement", CLOSED: "Closed",
};
const statusTone: Record<ReferralStatus, string> = {
  NEW: "slate", NEEDS_INFORMATION: "amber", READY_FOR_REVIEW: "blue", READY_TO_SEND: "teal",
  DELIVERY_INTERRUPTED: "red", AWAITING_ACKNOWLEDGEMENT: "violet", CLOSED: "green",
};
function nowIso() { return new Date().toISOString(); }
function timeLabel(iso: string) { return new Intl.DateTimeFormat("en-CA", { hour: "numeric", minute: "2-digit" }).format(new Date(iso)); }

function StatusPill({ status }: { status: ReferralStatus }) {
  return <span className={`status-pill ${statusTone[status]}`}><span className="status-dot" />{statusLabels[status]}</span>;
}
function ScopeBar() {
  return <div className="scope-bar" role="note"><span><Sparkles size={14} /> Synthetic records only</span><span>FHIR R4 · administrative workflow</span><span>No clinical decisions</span><span>Browser-persisted demo</span></div>;
}
function Logo() { return <div className="brand"><div className="brand-mark"><ArrowRight size={18} /></div><span>Clearpath</span></div>; }

function Queue({ state, onSelect }: { state: WorkspaceState; onSelect: (id: string) => void }) {
  return <aside className="queue-panel" aria-label="Referral queue"><div className="panel-heading"><div><p className="eyebrow">Referral queue</p><h2>Today&apos;s intake</h2></div><span className="count-badge">{state.referrals.filter((r) => r.status !== "CLOSED").length} open</span></div><div className="queue-list">{state.referrals.map((referral) => <button key={referral.id} className={`queue-item ${state.selectedReferralId === referral.id ? "active" : ""}`} onClick={() => onSelect(referral.id)}><div className="queue-top"><span className="mono">{referral.id}</span><span className={`mini-dot ${statusTone[referral.status]}`} /></div><strong>{referral.fields.find((f) => f.key === "patientName")?.value}</strong><span>{referral.packetName.replace(".txt", "")}</span><small>{statusLabels[referral.status]}</small></button>)}</div><div className="queue-note"><LockKeyhole size={16} /><div><strong>Local demo workspace</strong><p>State is kept in this browser only. No server or EHR is connected.</p></div></div></aside>;
}

function FieldRow({ field, selected, onSelect, onCorrect }: { field: ExtractedField; selected: boolean; onSelect: () => void; onCorrect: (key: FieldKey, value: string) => void }) {
  const [draft, setDraft] = useState(field.value);
  const low = field.confidence < .8;
  const missing = field.required && !field.value;
  return <div className={`field-row ${selected ? "selected" : ""} ${missing ? "missing" : ""}`}><button className="field-main" onClick={onSelect} aria-label={`Show source for ${field.label}`}><span className="field-label">{field.label}{field.required && <em>Required</em>}</span><span className="field-value">{field.value || "Not found in packet"}</span></button><div className="field-meta">{missing ? <span className="confidence missing"><CircleAlert size={14} />Missing</span> : <span className={`confidence ${low ? "low" : "high"}`}>{Math.round(field.confidence * 100)}%</span>}<button className="source-link" onClick={onSelect}><Link2 size={14} />{field.source ? `p.${field.source.page}` : "No source"}</button></div>{missing && <form className="inline-correction" onSubmit={(e) => { e.preventDefault(); if (draft.trim()) onCorrect(field.key, draft); }}><input aria-label={`Enter ${field.label}`} value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="Enter simulated callback number" /><button type="submit">Add</button></form>}</div>;
}

function DocumentViewer({ referral, selectedField }: { referral: Referral; selectedField: ExtractedField }) {
  return <section className="document-card" aria-label="Source packet"><div className="card-header"><div><span className="eyebrow">Source packet</span><h3>{referral.packetName}</h3></div><span className="file-chip"><FileText size={14} />TXT · {referral.pages.length} page{referral.pages.length > 1 ? "s" : ""}</span></div><div className="document-body">{referral.pages.map((page) => <article key={page.page} className="paper"><div className="paper-top"><span>Page {page.page}</span><span>synthetic</span></div><h4>{page.heading}</h4>{page.lines.map((line, index) => { const highlighted = selectedField.source?.page === page.page && selectedField.source.line === index + 1; return <p key={`${page.page}-${index}`} className={highlighted ? "highlight" : ""}>{line || "\u00a0"}{highlighted && <span className="source-marker">Source</span>}</p>; })}</article>)}</div><div className="provenance-strip"><Fingerprint size={16} /><div><strong>{selectedField.label}</strong><p>{selectedField.source ? `Page ${selectedField.source.page}, line ${selectedField.source.line} · “${selectedField.source.excerpt}”` : "No source evidence found. Staff-supplied data must record new provenance."}</p></div></div></section>;
}

function FhirPanel({ referral }: { referral: Referral }) {
  const result = validateReferral(referral); const [open, setOpen] = useState(false);
  const issueCount = result.missingFields.length + result.fhirErrors.length + (result.identityIssue ? 1 : 0);
  return <section className="fhir-card"><div className="fhir-summary"><div className={result.isValid ? "valid-icon" : "warning-icon"}>{result.isValid ? <ShieldCheck size={22} /> : <CircleAlert size={22} />}</div><div><span className="eyebrow">Interoperability check</span><h3>{result.isValid ? "FHIR R4 structure passes" : `${issueCount} issue${issueCount === 1 ? "" : "s"} to resolve`}</h3><p>ServiceRequest + Task · pinned to R4 (4.0.1)</p></div><button className="icon-button" onClick={() => setOpen(!open)} aria-expanded={open} aria-label="Toggle FHIR JSON"><ChevronDown size={18} /></button></div>{!result.isValid && <div className="validation-list">{result.identityIssue && <span><XCircle size={14} />{result.identityIssue}</span>}{result.missingFields.map((key) => <span key={key}><XCircle size={14} />Required field missing: {key}</span>)}{result.fhirErrors.map((error) => <span key={error}><XCircle size={14} />{error}</span>)}</div>}{open && <pre className="json-preview">{JSON.stringify({ serviceRequest: referral.serviceRequest, task: referral.task }, null, 2)}</pre>}</section>;
}

type DomainAction = (s: WorkspaceState, now: string) => { state: WorkspaceState; message: string };
function ActionPanel({ referral, run, message }: { referral: Referral; run: (fn: DomainAction) => void; message: string }) {
  const validation = validateReferral(referral); let primary: React.ReactNode;
  if (referral.status === "NEW") primary = <button className="primary-button" onClick={() => run(reviewExtraction)}><FileCheck2 size={17} />Review extraction</button>;
  else if (referral.status === "NEEDS_INFORMATION" && referral.identityStatus === "AMBIGUOUS") primary = <button className="primary-button" onClick={() => run(resolveIdentity)}><Fingerprint size={17} />Confirm synthetic identity</button>;
  else if (referral.status === "NEEDS_INFORMATION") primary = <div className="action-guidance"><CircleAlert size={17} /><span>Add the missing callback number above to continue.</span></div>;
  else if (referral.status === "READY_FOR_REVIEW") primary = <button className="primary-button" disabled={!validation.isValid} onClick={() => run((s, n) => assignReferral(s, "Alex Morgan", n))}><UserRoundCheck size={17} />Assign to me</button>;
  else if (referral.status === "READY_TO_SEND") primary = <button className="primary-button danger-outline" onClick={() => run((s, n) => deliverReferral(s, "INTERRUPT", n))}><Send size={17} />Send with outage simulation</button>;
  else if (referral.status === "DELIVERY_INTERRUPTED") primary = <button className="primary-button" onClick={() => run((s, n) => deliverReferral(s, "DELIVER", n))}><RefreshCw size={17} />Retry safely</button>;
  else if (referral.status === "AWAITING_ACKNOWLEDGEMENT") primary = <div className="button-pair"><button className="secondary-button" onClick={() => run((s, n) => deliverReferral(s, "DELIVER", n))}><ShieldCheck size={17} />Prove duplicate prevention</button><button className="primary-button" onClick={() => run(acknowledgeReferral)}><Check size={17} />Simulate acknowledgement</button></div>;
  else primary = <div className="complete-block"><CheckCircle2 size={24} /><div><strong>Administrative handoff closed</strong><p>One receiving referral, acknowledged by the simulated clinic.</p></div></div>;
  return <div className="action-panel"><div className="action-copy"><span className="eyebrow">Next safe action</span><div aria-live="polite">{message || "Complete each gate in order; invalid transitions are blocked."}</div></div>{primary}</div>;
}

function Timeline({ referral }: { referral: Referral }) {
  return <section className="timeline-card"><div className="card-header"><div><span className="eyebrow">Attributable history</span><h3>{referral.audit.length} recorded events</h3></div><History size={19} /></div><ol className="timeline">{[...referral.audit].reverse().map((item) => <li key={item.id}><span className="timeline-dot" /><div className="timeline-event"><div><strong>{item.action.replaceAll("_", " ").toLowerCase()}</strong><time>{timeLabel(item.at)}</time></div><p>{item.detail}</p><small>{item.actor}</small></div></li>)}</ol></section>;
}

function Workbench({ state, setState, message, setMessage }: { state: WorkspaceState; setState: (s: WorkspaceState) => void; message: string; setMessage: (v: string) => void }) {
  const referral = state.referrals.find((r) => r.id === state.selectedReferralId)!; const [fieldKey, setFieldKey] = useState<FieldKey>("patientName"); const selectedField = referral.fields.find((f) => f.key === fieldKey) ?? referral.fields[0];
  const run = (fn: DomainAction) => { const result = fn(state, nowIso()); setState(result.state); setMessage(result.message); };
  return <div className="workspace-grid"><Queue state={state} onSelect={(id) => { setState({ ...state, selectedReferralId: id }); setMessage(""); }} /><main className="workspace-main" id="main-content"><header className="referral-header"><div><div className="header-kicker"><span className="mono">{referral.id}</span><StatusPill status={referral.status} /></div><h1>{referral.fields.find((f) => f.key === "patientName")?.value}</h1><p>Administrative specialist referral · received from Lakeshore Family Practice</p></div><div className="owner-block"><span>Owner</span><strong>{referral.assignee ?? "Unassigned"}</strong></div></header><div className="review-layout"><DocumentViewer referral={referral} selectedField={selectedField} /><div className="review-column"><section className="fields-card"><div className="card-header"><div><span className="eyebrow">Deterministic extraction</span><h3>Review {referral.fields.length} fields</h3></div><span className="review-chip">Staff review required</span></div><div className="fields-list">{referral.fields.map((field) => <FieldRow key={field.key} field={field} selected={selectedField.key === field.key} onSelect={() => setFieldKey(field.key)} onCorrect={(key, value) => run((s, n) => correctField(s, key, value, n))} />)}</div></section><FhirPanel referral={referral} /></div></div><ActionPanel referral={referral} run={run} message={message} /><Timeline referral={referral} /></main></div>;
}

function Metric({ value, label, detail, icon }: { value: string; label: string; detail?: string; icon: React.ReactNode }) { return <div className="metric-card"><div className="metric-icon">{icon}</div><strong>{value}</strong><span>{label}</span>{detail && <small>{detail}</small>}</div>; }
function Handoffs({ state }: { state: WorkspaceState }) {
  const attempts = state.referrals.flatMap((r) => r.deliveryAttempts.map((a) => ({ ...a, referralId: r.id })));
  return <main className="standard-page" id="main-content"><div className="page-title"><span className="eyebrow">Reliability control room</span><h1>Handoff ledger</h1><p>Every simulated receiver attempt carries one stable idempotency key.</p></div><div className="metric-row"><Metric value={`${attempts.filter((a) => a.outcome === "DELIVERED").length}`} label="Accepted deliveries" icon={<Send />} /><Metric value={`${attempts.filter((a) => a.outcome === "DUPLICATE_SUPPRESSED").length}`} label="Duplicates suppressed" icon={<ShieldCheck />} /><Metric value={`${attempts.filter((a) => a.outcome === "INTERRUPTED").length}`} label="Interrupted attempts" icon={<Activity />} /></div><section className="table-card"><div className="card-header"><div><span className="eyebrow">Delivery attempts</span><h3>Receiver activity</h3></div></div>{attempts.length ? <div className="attempt-table" role="table"><div className="attempt-head" role="row"><span>Referral</span><span>Outcome</span><span>Idempotency key</span><span>Receiver evidence</span></div>{[...attempts].reverse().map((a) => <div className="attempt-row" role="row" key={a.id}><span className="mono">{a.referralId}</span><span className={`outcome ${a.outcome.toLowerCase()}`}>{a.outcome.replaceAll("_", " ")}</span><code>{a.idempotencyKey}</code><span>{a.receiverMessage}</span></div>)}</div> : <div className="empty-state"><Inbox size={30} /><h3>No delivery attempts yet</h3><p>Run the guided referral flow to create interrupted, successful, and duplicate-suppressed attempts.</p></div>}</section></main>;
}

function Evidence({ state }: { state: WorkspaceState }) {
  const selected = state.referrals.find((r) => r.id === state.selectedReferralId)!; const corrections = selected.audit.filter((e) => e.action === "FIELD_CORRECTED").length; const duplicates = selected.deliveryAttempts.filter((a) => a.outcome === "DUPLICATE_SUPPRESSED").length; const elapsed = selected.status === "CLOSED" ? Math.max(1, Math.round((new Date(selected.updatedAt).getTime() - new Date(selected.benchmarkStartedAt).getTime()) / 60000)) : null;
  return <main className="standard-page" id="main-content"><div className="page-title"><span className="eyebrow">Reproducible evidence</span><h1>Demo measures</h1><p>Transparent synthetic-fixture results, not hospital outcomes or clinical validation.</p></div><div className="metric-row four"><Metric value={`${(BENCHMARK_RESULT.extractionAccuracy * 100).toFixed(1)}%`} label="Field extraction accuracy" detail={`${BENCHMARK_RESULT.correctFields} / ${BENCHMARK_RESULT.fields} fields · ${BENCHMARK_RESULT.packets} generated conformance cases`} icon={<FileCheck2 />} /><Metric value={`${(BENCHMARK_RESULT.correctionRate * 100).toFixed(1)}%`} label="Staff correction rate" detail={`${BENCHMARK_RESULT.correctionsRequired} / ${BENCHMARK_RESULT.fields} fields · deterministic fixture suite`} icon={<UserRoundCheck />} /><Metric value={`${BENCHMARK_RESULT.duplicateDeliveryErrors}`} label="Duplicate delivery errors" detail={`${BENCHMARK_RESULT.retryScenarios} retry scenarios · receiver-backed keys`} icon={<ShieldCheck />} /><Metric value={elapsed ? `${elapsed} min` : "In progress"} label="Current demo completion" detail={`${corrections} correction · ${duplicates} duplicate blocked`} icon={<Clock3 />} /></div><section className="evidence-grid"><div className="evidence-card"><span className="eyebrow">Conditions</span><h3>Synthetic conformance suite v1</h3><ul><li>{BENCHMARK_RESULT.packets} generated parser conformance cases</li><li>6 required fields per case</li><li>Exact normalized-value comparison</li><li>{BENCHMARK_RESULT.retryScenarios} receiver-accepted/response-lost scenarios</li><li>Run locally with <code>npm run benchmark</code></li></ul></div><div className="evidence-card"><span className="eyebrow">Interpretation</span><h3>What this does—and doesn&apos;t—show</h3><p>The suite exercises deterministic fixtures, source links, validation, and safe retry behavior. It is not a separately authored held-out dataset and does not establish real-world clinical accuracy, production scale, privacy compliance, or user adoption.</p></div></section></main>;
}

function SystemPage() { return <main className="standard-page" id="main-content"><div className="page-title"><span className="eyebrow">System boundaries</span><h1>How Clearpath works</h1><p>A zero-secret, browser-persisted interoperability demonstration.</p></div><div className="architecture-flow"><div><FileText /><strong>Synthetic packet</strong><span>Authored text fixtures</span></div><ArrowRight /><div><Fingerprint /><strong>Extractor</strong><span>Deterministic + provenance</span></div><ArrowRight /><div><ShieldCheck /><strong>Review gates</strong><span>Human correction + R4 validation</span></div><ArrowRight /><div><Send /><strong>Simulated clinic</strong><span>Idempotent handoff</span></div></div><section className="boundary-grid"><div><h3>Inside the demo</h3><ul><li>Typed TypeScript domain contracts</li><li>Boundary validation for persisted state</li><li>FHIR R4 ServiceRequest and Task projections</li><li>Deterministic transition and delivery logic</li><li>Attributable local audit history</li></ul></div><div><h3>Explicitly outside scope</h3><ul><li>Real patient health information</li><li>Clinical diagnosis, urgency, or treatment</li><li>Live EHR or hospital connectivity</li><li>Authentication and production access control</li><li>Compliance or interoperability certification</li></ul></div></section></main>; }

export function ReferralWorkbench() {
  const [state, setState] = useState<WorkspaceState>(() => createSeedState()); const [view, setView] = useState<View>("workbench"); const [message, setMessage] = useState(""); const [hydrated, setHydrated] = useState(false);
  useEffect(() => { queueMicrotask(() => { const raw = localStorage.getItem(STORAGE_KEY); if (raw) { try { const parsed = workspaceSchema.safeParse(JSON.parse(raw)); if (parsed.success) setState(parsed.data); } catch { localStorage.removeItem(STORAGE_KEY); } } setHydrated(true); }); }, []);
  useEffect(() => { if (hydrated) localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }, [state, hydrated]);
  const progress = useMemo(() => { const r = state.referrals.find((x) => x.id === state.selectedReferralId)!; return ({ NEW: 14, NEEDS_INFORMATION: 28, READY_FOR_REVIEW: 48, READY_TO_SEND: 63, DELIVERY_INTERRUPTED: 74, AWAITING_ACKNOWLEDGEMENT: 88, CLOSED: 100 } as Record<ReferralStatus, number>)[r.status]; }, [state]);
  const reset = () => { const next = createSeedState(); setState(next); setMessage("Demo restored to reproducible seed data."); localStorage.removeItem(STORAGE_KEY); setView("workbench"); };
  return <div className="app-shell"><a className="skip-link" href="#main-content">Skip to main content</a><ScopeBar /><header className="topbar"><Logo /><nav aria-label="Primary"><button className={view === "workbench" ? "active" : ""} onClick={() => setView("workbench")}>Workbench</button><button className={view === "handoffs" ? "active" : ""} onClick={() => setView("handoffs")}>Handoffs</button><button className={view === "evidence" ? "active" : ""} onClick={() => setView("evidence")}>Evidence</button><button className={view === "system" ? "active" : ""} onClick={() => setView("system")}>System</button></nav><div className="top-actions"><div className="progress-mini" title="Selected referral progress"><span style={{ width: `${progress}%` }} /></div><button className="reset-button" onClick={reset}><RotateCcw size={15} />Reset demo</button><div className="avatar" aria-label="Alex Morgan">AM</div></div></header>{view === "workbench" && <Workbench state={state} setState={setState} message={message} setMessage={setMessage} />}{view === "handoffs" && <Handoffs state={state} />}{view === "evidence" && <Evidence state={state} />}{view === "system" && <SystemPage />}<footer><span>Clearpath Referrals · portfolio demonstration</span><span>Not a hospital integration or compliance certification</span></footer></div>;
}
